import Main from "@/components/Main";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <h1>My App</h1>
        <Link href="/upload">Image upload</Link>
      </Main>
    </div>
  );
}
